[package]
name = "button-blink"
version = "0.1.0"
authors = ["Sondre Lefsaker <sondrele@stud.ntnu.no>"]

[target.thumbv7m-none-eabi.dependencies.emlib]
git = "https://github.com/sondrele/emlib.git"
rev = "3ebfb852987a8f73c9a7db2fbd0d496a85271a9f"
features = ["stk3700"]
